### PR TITLE
Repair ECL support

### PR DESCRIPTION
**Pull request by spaghettisalat**
This support for current versions of ECL is broken, storing arbitrary objects doesn't work. Besides, custom functions for the slot-definition-* methods are not needed anymore, since ECL includes them.

### CODE REVIEW

**Comment by kaiserprogrammer** [comment]
+ please include

**Comment by spaghettisalat** [comment]
Simplest example of code which doesn't work:

```lisp
(defclass test () ((test :initform nil)))
(cl-store:store (make-instance 'test) "/home/marius/test")
(cl-store:restore "/home/marius/test")
```

This is caused by the fact that earlier versions of ECL used a non-standard meta-object protocol. In particular, functions such as slot-definition, slot-definition-name, ... where not defined, which is why cl-store emulates them in the file ecl/mop.lisp. This has however been changed quite a while ago (I don't know exactly when, since the CHANGELOG file of ECL doesn't mention the change) and thus all the functions that cl-store defines in ecl/mop.lisp do not work anymore, and neither are they needed.

**Comment by yaroe** [comment]
+1 merge

**Comment by ilya-fiveisky** [comment]
Sorry for asking but are there problems in this fix preventing it from merging?

**Comment by skypher** [comment]
Wow, sorry everyone for dropping the ball on this, and thanks for the reminder! Merging.

**Pull request merged**
